### ISSUE TITLE
Error linking .a file with backtrace-rs >0.3.30 on OSX

### ISSUE THREAD

**Issue by glebpom** [rust-lang/backtrace-rs#218]
I'm building `.a` file from the rust code. It fails to properly link with the Swift app on OSX with the following error:
```
duplicate symbol _macho_file_to_host_u16 in:
```
There were more errors on a 0.3.31, most of them were probably fixed on 0.3.32

**Comment by mciantyre** [comment]
I've been having this issue as well. It looks like #214 added some prefixes to these symbols, but it missed `_macho_file_to_host_u16`. If it's OK, I've prepared #219 to make the addition.

We can show the duplicated symbol with the following crate setup:

Crate `foobar` uses `backtrace`, and it exports all `backtrace` symbols with a `pub use backtrace::*` at the top of `lib.rs`:

```toml
[package]
name = "foobar"
version = "0.1.0"
authors = ["Author <e@mail.com>"]
edition = "2018"

[dependencies]
backtrace = "0.3"

[workspace]
members = [
    "foobar-ffi",
]
```

Suppose `foobar-ffi` exposes the FFI of `foobar`. It simply re-exports all of foobar with `pub use foobar::*` at the top to `lib.rs`:

```toml
[package]
name = "foobar-ffi"
version = "0.1.0"
authors = ["Author <e@mail.com>"]
edition = "2018"

[dependencies]
foobar = { path = "../" }

[lib]
crate-type = ["staticlib"]
```

Building this, and expecting the static lib from `foobar-ffi` shows the duplicated symbol:

```
$ cargo build -p foobar-ffi
$ nm target/debug/libfoobar_ffi.a | grep _macho_file_to_host_u16
0000000000000000 T _macho_file_to_host_u16
0000000000000000 T _macho_file_to_host_u16
```

With #219 in place, there's no duplicated symbol (one of them will be prefixed with `_rbt_` in this demonstration).
