### ISSUE TITLE
libbacktrace cannot be updated in Rust's libstd because of memchr dependency

### ISSUE THREAD

**Issue by nielx** [rust-lang/backtrace-rs#432]
I suppose that this is more a tracking issue for a downstream problem, but it seems to make sense to raise it here.

In libbacktrace 0.2.60, the dependency on [object ](https://github.com/gimli-rs/object/) has been raised to 0.25.0. This release contains an [unconditional dependency](https://github.com/gimli-rs/object/commit/de7ecdd13776b687ae435f499fe500a35afc8b73#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) on [memchr](https://github.com/BurntSushi/memchr). This crate does not support the `rustc-std-workspace-core` workaround.

If the backtrace version shipped with `rustc` needs to be set higher than 0.3.59, this problem needs to be solved.

CC: @BurntSushi CC: @philipc @fitzgen

**Comment by BurntSushi** [comment]
> rustc-std-workspace-core

I'm not sure what this is, but if there's a non-invasive patch for memchr, I would be happy to accept a PR and get a release out quickly.

Of course, without looking carefully, it's likely that memchr could be made optional since all of its public APIs have corresponding simple and naive implementations.

**Comment by alexcrichton** [comment]
I'll work on sending a PR to `memchr` for this soon. @BurntSushi for reference the changes should be entirely isolated to `Cargo.toml` and look of this shape:


```toml
[dependencies]
# Internal feature, only used when building as part of libstd, not part of the
# stable interface of this crate.
core = { version = '1.0.0', optional = true, package = 'rustc-std-workspace-core' }
alloc = { version = '1.0.0', optional = true, package = 'rustc-std-workspace-alloc' }
compiler_builtins = { version = '0.1.2', optional = true }

[features]
# Internal feature, only used when building as part of libstd, not part of the
# stable interface of this crate.
rustc-dep-of-std = ['core', 'alloc', 'compiler_builtins']
```

The fix at that point would be to add a line [here](https://github.com/gimli-rs/object/blob/c33bf5a06816ca71d798924045002b177d732e5f/Cargo.toml#L84) enabling the `rustc-dep-of-std` feature for `memchr` when `object`'s own `rustc-dep-of-std` feature is active.
